// Mock data for banners
export const banners = [
  {
    id: 1,
    title: "¡Semana Verde!",
    subtitle: "Hasta 50% de descuento en productos ecológicos",
    description: "Descubre nuestra selección de productos sostenibles",
    image: "/brand/logo.webp",
    cta: "Comprar Ahora",
    href: "/departments/eco-home",
    bgColor: "bg-gradient-to-r from-primary to-primary-dark",
  },
  {
    id: 2,
    title: "Nuevo: Línea de Cuidado Personal",
    subtitle: "Productos naturales para tu rutina diaria",
    description: "100% orgánicos y libres de químicos",
    image: "/brand/logo.webp",
    cta: "Explorar",
    href: "/departments/personal-care",
    bgColor: "bg-gradient-to-r from-success to-secondary",
  },
  {
    id: 3,
    title: "Intercambio Sostenible",
    subtitle: "Dale nueva vida a tus productos",
    description: "Intercambia, dona o vende productos usados",
    image: "/brand/logo.webp",
    cta: "Comenzar",
    href: "/products/exchange",
    bgColor: "bg-gradient-to-r from-info to-primary-light",
  },
];

// Mock data for featured categories
export const featuredCategories = [
  {
    id: 1,
    name: "Hogar Ecológico",
    count: "150+ productos",
    image: "/brand/icon.webp",
    href: "/departments/eco-home",
  },
  {
    id: 2,
    name: "Cuidado Personal",
    count: "80+ productos",
    image: "/brand/icon.webp",
    href: "/departments/personal-care",
  },
  {
    id: 3,
    name: "Moda Sostenible",
    count: "200+ productos",
    image: "/brand/icon.webp",
    href: "/departments/fashion",
  },
  {
    id: 4,
    name: "Alimentación",
    count: "120+ productos",
    image: "/brand/icon.webp",
    href: "/departments/food",
  },
];

// Mock data for best ranked stores
export const bestRankedStores = [
  {
    id: 1,
    name: "EcoVerde Premium",
    rating: 4.9,
    reviews: 1250,
    products: 156,
    image: "/brand/icon.webp",
    badge: "Top Rated",
    location: "Barcelona",
    verified: true,
  },
  {
    id: 2,
    name: "Natura Sostenible",
    rating: 4.8,
    reviews: 890,
    products: 203,
    image: "/brand/icon.webp",
    badge: "Certificado",
    location: "Madrid",
    verified: true,
  },
  {
    id: 3,
    name: "Zero Waste Shop",
    rating: 4.7,
    reviews: 645,
    products: 89,
    image: "/brand/icon.webp",
    badge: "Eco Expert",
    location: "Valencia",
    verified: true,
  },
  {
    id: 4,
    name: "Green Living Co",
    rating: 4.6,
    reviews: 523,
    products: 134,
    image: "/brand/icon.webp",
    badge: "Popular",
    location: "Sevilla",
    verified: false,
  },
];

// Mock data for best store products
export const bestStoreProducts = [
  {
    id: 1,
    name: "Detergente Ecológico Premium",
    brand: "EcoClean",
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.9,
    reviews: 456,
    image: "/brand/icon.webp",
    badge: "Bestseller",
    store: "EcoVerde Premium",
    discount: 17,
  },
  {
    id: 2,
    name: "Jabón Artesanal de Lavanda",
    brand: "Natura Soap",
    price: 8.99,
    originalPrice: null,
    rating: 4.8,
    reviews: 234,
    image: "/brand/icon.webp",
    badge: "Orgánico",
    store: "Natura Sostenible",
    discount: 0,
  },
  {
    id: 3,
    name: "Champú Sólido Zero Waste",
    brand: "ZeroWaste",
    price: 12.5,
    originalPrice: 15.99,
    rating: 4.7,
    reviews: 189,
    image: "/brand/icon.webp",
    badge: "Zero Waste",
    store: "Zero Waste Shop",
    discount: 22,
  },
  {
    id: 4,
    name: "Cepillo Bambú Premium",
    brand: "BambooBrush",
    price: 9.99,
    originalPrice: null,
    rating: 4.6,
    reviews: 167,
    image: "/brand/icon.webp",
    badge: "Bambú",
    store: "Green Living Co",
    discount: 0,
  },
];

// Mock data for second hand products
export const secondHandProducts = [
  {
    id: 1,
    name: "Licuadora Vitamix (Como Nueva)",
    brand: "Vitamix",
    price: 189.99,
    originalPrice: 350.0,
    rating: 4.8,
    reviews: 23,
    image: "/brand/icon.webp",
    badge: "Segunda Mano",
    condition: "Excelente",
    seller: "María G.",
    savings: 46,
  },
  {
    id: 2,
    name: "Juego de Sartenes Ecológicas",
    brand: "GreenPan",
    price: 89.5,
    originalPrice: 159.99,
    rating: 4.5,
    reviews: 12,
    image: "/brand/icon.webp",
    badge: "Usado",
    condition: "Muy Bueno",
    seller: "Carlos M.",
    savings: 44,
  },
  {
    id: 3,
    name: "Purificador de Aire HEPA",
    brand: "Dyson",
    price: 245.0,
    originalPrice: 399.99,
    rating: 4.7,
    reviews: 18,
    image: "/brand/icon.webp",
    badge: "Reacondicionado",
    condition: "Excelente",
    seller: "Ana L.",
    savings: 39,
  },
  {
    id: 4,
    name: "Bicicleta Eléctrica Urbana",
    brand: "E-Bike Co",
    price: 899.0,
    originalPrice: 1299.99,
    rating: 4.6,
    reviews: 7,
    image: "/brand/icon.webp",
    badge: "Segunda Mano",
    condition: "Bueno",
    seller: "Pedro R.",
    savings: 31,
  },
];

// Mock data for exchangeable products
export const exchangeableProducts = [
  {
    id: 1,
    name: "Libros de Jardinería Ecológica",
    brand: "Varios Autores",
    exchangeFor: "Semillas orgánicas",
    category: "Libros",
    image: "/brand/icon.webp",
    badge: "Intercambio",
    owner: "Laura S.",
    condition: "Muy Bueno",
    interested: 8,
  },
  {
    id: 2,
    name: "Macetas de Terracota Vintage",
    brand: "Artesanal",
    exchangeFor: "Plantas de interior",
    category: "Jardinería",
    image: "/brand/icon.webp",
    badge: "Trueque",
    owner: "Miguel A.",
    condition: "Excelente",
    interested: 12,
  },
  {
    id: 3,
    name: "Ropa Bebé Orgánica (6-12m)",
    brand: "EcoBaby",
    exchangeFor: "Juguetes educativos",
    category: "Ropa",
    image: "/brand/icon.webp",
    badge: "Intercambio",
    owner: "Carmen V.",
    condition: "Como Nuevo",
    interested: 15,
  },
  {
    id: 4,
    name: "Herramientas de Jardín",
    brand: "Garden Tools",
    exchangeFor: "Compostador",
    category: "Herramientas",
    image: "/brand/icon.webp",
    badge: "Trueque",
    owner: "José M.",
    condition: "Bueno",
    interested: 5,
  },
];

// Mock data for ads
export const ads = [
  {
    id: 1,
    title: "¡Nuevo! Línea de Cosmética Natural",
    subtitle: "100% Orgánica y Vegana",
    image: "/brand/logo.webp",
    cta: "Descubrir",
    href: "/departments/personal-care",
    bgColor: "bg-gradient-to-r from-primary/20 to-success/20",
    textColor: "text-primary",
  },
  {
    id: 2,
    title: "Ahorra hasta 40% en Electrodomésticos",
    subtitle: "Eficiencia energética A+++",
    image: "/brand/logo.webp",
    cta: "Ver Ofertas",
    href: "/departments/home-appliances",
    bgColor: "bg-gradient-to-r from-info/20 to-primary-light/20",
    textColor: "text-info",
  },
  {
    id: 3,
    title: "Programa de Reciclaje EKORU",
    subtitle: "Intercambia y gana puntos verdes",
    image: "/brand/logo.webp",
    cta: "Participar",
    href: "/programs/recycle",
    bgColor: "bg-gradient-to-r from-success/20 to-secondary/20",
    textColor: "text-success",
  },
];
