import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import AppWrapper from "./appWrapper";

const cabin = Cabin({
  variable: "--font-cabin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cabin.variable} antialiased`}>
        <ToastContainer
          theme="light"
          autoClose={2500}
          pauseOnHover
          position="top-center"
          closeOnClick
        />
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
